// The cache identity is computed by the server; browser keys cannot overwrite another image.
export async function imageKey(model: string, messages: unknown) {
 // A ruler portrait is reusable across birthdays and adjacent years. Style/subject/country remain part of its identity.
 if(Array.isArray(messages)&&messages.length===1&&typeof messages[0]?.content==='string'&&messages[0].content.startsWith('Formal painted state portrait, oil painting,')){
  messages=[{...messages[0],content:messages[0].content.replace(/, (?:\d+ years old|middle-aged)/,', adult').replace(/, year \d+\./,'.')}];
 }
 const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify({version:1,model,messages})));
 return Array.from(new Uint8Array(digest),b=>b.toString(16).padStart(2,'0')).join('');
}
export async function cachedImage(admin: any,userId: string,guest: boolean,body: any,orKey: string) {
 if(body.model!=='google/gemini-3.1-flash-image'||!Array.isArray(body.messages)||body.messages.length!==1||body.messages[0]?.role!=='user'||typeof body.messages[0]?.content!=='string'||body.messages[0].content.length>4000)return {status:400,data:{error:'bad_payload'}};
 const key=await imageKey(body.model,body.messages);
 const balance=async()=>{
  if(guest){const r=await admin.rpc('mobile_image_status',{p_user:userId});return r.data;}
  const r=await admin.from('profiles').select('image_generations_remaining').eq('id',userId).single();return r.data?.image_generations_remaining;
 };
 const {data:claim,error}=await admin.rpc('shared_image_claim',{p_user:userId,p_key:key,p_guest:guest});
 if(error||!claim)return {status:503,data:{error:'quota_unavailable'}};
 const reply=async (url:string,hit:boolean,left:number)=>{
  if(url.startsWith('storage:')){const signed=await admin.storage.from('generated-images').createSignedUrl(url.slice(8),3600);if(signed.error)return {status:503,data:{error:'image_save_failed'}};url=signed.data.signedUrl;}
  return {status:200,data:{choices:[{message:{images:[{image_url:{url}}]}}],image_generations_remaining:left,cache_hit:hit}};
 };
 if(claim.hit)return reply(claim.url,true,await balance());
 if(claim.error)return {status:claim.error==='image_busy'?409:402,data:{error:claim.error}};
 let savedUrl:string|null=null;
 try{
  const response=await fetch('https://openrouter.ai/api/v1/chat/completions',{
   method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+orKey},signal:AbortSignal.timeout(90000),
   body:JSON.stringify({model:body.model,messages:body.messages,modalities:['image','text'],max_tokens:1000})
  });
  const result=await response.json();
  const url=result.choices?.[0]?.message?.images?.[0]?.image_url?.url;
  if(!response.ok||typeof url!=='string')return {status:502,data:{error:'ai_unavailable'}};
  const match=/^data:(image\/(?:png|jpeg|webp));base64,([A-Za-z0-9+/=\s]+)$/.exec(url);
  if(!match||url.length>14000000)return {status:502,data:{error:'invalid_image'}};
  // Save the generated bytes first. Storage failures must not cause another paid generation.
  savedUrl=url;
  const bytes=Uint8Array.from(atob(match[2]),c=>c.charCodeAt(0));
  const extension=match[1].split('/')[1];const path=key+'.'+extension;
  const upload=await admin.storage.from('generated-images').upload(path,bytes,{contentType:match[1],upsert:false,cacheControl:'31536000'});
  if(!upload.error)savedUrl='storage:'+path;
  const finish=await admin.rpc('shared_image_finish',{p_user:userId,p_key:key,p_ticket:claim.reservation,p_url:savedUrl});
  if(finish.error||finish.data!==true)throw Error('cache_write_failed');
  return reply(savedUrl,false,claim.remaining);
 }catch(error){
  // A second DB attempt also persists the generated image if Storage is temporarily down.
  const finish=await admin.rpc('shared_image_finish',{p_user:userId,p_key:key,p_ticket:claim.reservation,p_url:savedUrl});
  if(savedUrl&&!finish.error&&finish.data)return reply(savedUrl,false,claim.remaining);
  return {status:503,data:{error:'image_save_failed'}};
 }finally{
  if(savedUrl===null)await admin.rpc('shared_image_finish',{p_user:userId,p_key:key,p_ticket:claim.reservation,p_url:null});
 }
}

export async function resolveImages(admin:any,paths:unknown){
 if(!Array.isArray(paths)||paths.length>100||paths.some(p=>typeof p!=='string'||!/^[a-f0-9]{64}\.(png|jpeg|webp)$/.test(p)))return {status:400,data:{error:'bad_payload'}};
 const urls:Record<string,string>={};
 for(const path of [...new Set(paths)]){
  const row=await admin.from('shared_images').select('cache_key').eq('asset_url','storage:'+path).eq('status','ready').maybeSingle();
  if(!row.data)continue;
  const signed=await admin.storage.from('generated-images').createSignedUrl(path,3600);
  if(!signed.error)urls[path]=signed.data.signedUrl;
 }
 return {status:200,data:{urls}};
}

// Lookup never claims credits and never contacts the generation provider.
export async function lookupImages(admin:any,requests:unknown){
 if(!Array.isArray(requests)||requests.length>100||requests.some(r=>typeof r?.id!=='string'||r.id.length>160||r.model!=='google/gemini-3.1-flash-image'||!Array.isArray(r.messages)||r.messages.length!==1||r.messages[0]?.role!=='user'||typeof r.messages[0]?.content!=='string'||r.messages[0].content.length>4000))return {status:400,data:{error:'bad_payload'}};
 const identities=await Promise.all(requests.map(async r=>({id:r.id,key:await imageKey(r.model,r.messages)})));
 const urls:Record<string,string>={};
 if(!identities.length)return {status:200,data:{urls}};
 const result=await admin.from('shared_images').select('cache_key,asset_url').eq('status','ready').in('cache_key',identities.map(r=>r.key));
 if(result.error)return {status:503,data:{error:'image_lookup_failed'}};
 for(const row of result.data||[]){
  let url=row.asset_url;
  if(typeof url!=='string')continue;
  if(url.startsWith('storage:')){const signed=await admin.storage.from('generated-images').createSignedUrl(url.slice(8),3600);if(signed.error)return {status:503,data:{error:'image_lookup_failed'}};url=signed.data.signedUrl;}
  for(const item of identities)if(item.key===row.cache_key)urls[item.id]=url;
 }
 return {status:200,data:{urls}};
}
