import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import {imageKey,lookupImages} from '../supabase/functions/_shared/images.ts';
const read=p=>readFileSync(p,'utf8');
const game=read('economy-game.js'),ai=read('political-ai.js');
const defaults=new Function(game.slice(game.indexOf('const COUNTRY_DEFAULTS'),game.indexOf('function placeholderCountry'))+';return COUNTRY_DEFAULTS;')();
const fixture=JSON.parse(read('scenario_orders1852.json'));
const world=Object.fromEntries(Object.keys(fixture.countryColors).map(n=>[n,{...(fixture.countryProfiles?.[n]||defaults[n]||{}),displayName:(fixture.countryProfiles?.[n]||defaults[n])?.displayName||n}]));
const builder=ai.slice(ai.indexOf('function buildPersonPortraitPrompt'),ai.indexOf('let portraitGenerating'));
const promptFor=new Function('countries','year',builder+'return buildPersonPortraitPrompt;')(world,1852);
for(const n of ['Королевство Пруссия','Великобритания'])for(const role of ['ruler','pm'])if(promptFor(n,role))console.log(n,role,await imageKey('google/gemini-3.1-flash-image',[{role:'user',content:promptFor(n,role)}]));
let sent=[],resolveFetch,saveCount=0,refreshCount=0;
const context={countries:world,year:1852,gsUser:{id:'u',isAnonymous:false},sb:{},gameStarted:true,GS_CONFIG:{API_BASE:'mock',SUPABASE_ANON_KEY:'test'},authToken:async()=> 'token',console,Event,HTMLImageElement:class{},localStorage:{getItem:()=>null},listSaves:()=>[],document:{addEventListener(){},getElementById:()=>null},loadGameSlot(){},deleteSave(){},startGame(){},renderRulerPortrait(){refreshCount++},saveGame(){saveCount++},fetch:async(_,options)=>{sent.push(JSON.parse(options.body));return await new Promise(r=>resolveFetch=r);}};
context.window=context;context.addEventListener=()=>{};context.dispatchEvent=()=>{};
vm.createContext(context);vm.runInContext(builder+read('cloud-library.js'),context);
let hydrate=context.gsHydratePortraits();await new Promise(r=>setImmediate(r));
assert.equal(sent[0].operation,'lookup_images');
const requests=sent[0].requests,pm=requests.find(r=>r.messages[0].content.includes('Мантейф')||r.messages[0].content.includes('Мантейфел'));
const victoria=requests.find(r=>r.messages[0].content.includes('Виктория'));
assert.ok(victoria);const chosen=pm||requests.find(r=>r.messages[0].content===promptFor('Королевство Пруссия','pm'));
assert.ok(chosen);
resolveFetch({ok:true,json:async()=>({urls:{[chosen.id]:'https://test/pm',[victoria.id]:'https://test/queen'}})});await hydrate;
assert.equal(world['Королевство Пруссия'].pmPortrait,'https://test/pm');assert.equal(world['Великобритания'].portrait,'https://test/queen');assert.equal(saveCount,1);assert.equal(refreshCount,1);
world['Великобритания'].portrait=null;
hydrate=context.gsHydratePortraits();await new Promise(r=>setImmediate(r));const old=sent.at(-1).requests.find(r=>r.messages[0].content.includes('Виктория'));context.countries={New:{ruler:'New'}};resolveFetch({ok:true,json:async()=>({urls:{[old.id]:'https://test/stale'}})});await hydrate;assert.equal(world['Великобритания'].portrait,null,'A response for an old campaign must be discarded');
let rpcCalls=0,providerCalls=0;
const oldFetch=globalThis.fetch;globalThis.fetch=async()=>{providerCalls++;throw Error('Generation forbidden')};
const key=await imageKey(requests[0].model,requests[0].messages);
const admin={rpc:()=>{rpcCalls++;throw Error('Debit forbidden')},from:()=>({select:()=>({eq:()=>({in:async()=>({data:[{cache_key:key,asset_url:'storage:test.png'}]})})})}),storage:{from:()=>({createSignedUrl:async()=>({data:{signedUrl:'https://test/signed'}})})}};
try{const result=await lookupImages(admin,[requests[0]]);assert.equal(result.data.urls[requests[0].id],'https://test/signed');assert.equal(rpcCalls,0);assert.equal(providerCalls,0);assert.equal((await lookupImages(admin,[{id:'x'}])).status,400);}finally{globalThis.fetch=oldFetch;}
// Sign-in lists remote parties without copying full states into localStorage.
const stored=new Map();context.countries=world;context.localStorage={getItem:k=>stored.get(k)||null,setItem:(k,v)=>stored.set(k,v),key:()=>null,length:0};
context.getMapsIndex=()=>[];context.getScenariosIndex=()=>[];
context.sb={from:()=>({select(){return this},eq(){return this},then(resolve,reject){return Promise.resolve({data:[]}).then(resolve,reject)}})};
context.cloudListSaves=async()=>[{id:'remote-party',country:'Австрия',savedAt:10}];
context.cloudLoad=()=>{throw Error('A full party must only load when opened')};
assert.equal(await context.gsSyncLibrary(),true);
assert.equal(context.listSaves().find(s=>s.id==='remote-party').country,'Австрия');
assert.equal([...stored.keys()].some(k=>k.startsWith('gs_economyworld_save_')),false);
console.log('Shared portraits: campaign hydration, stale responses and lookup without generation or debit passed.');
